export default {
    decorators: {
        addons: {
            prefix: false,
            suffix: false,
        },
        before: false,
        between: false,
        after: false,
        tooltip: false,
        description: false,
    },
    data: {
        default: false,
        submit: false,
        items: {
            list: false,
            json: false,
            endpoint: false,
        },
        object: false,
        nested: false,
    },
    layout: {
        size: false,
        columns: false,
        align: {
            left: false,
            right: false,
        },
        view: {
            tabs: false,
            blocks: false,
        },
        minWidth: false,
        maxWidth: false,
        gap: false,
        padding: false,
        hideRows: false,
        rowWrap: false,
        stickyRows: false,
        hideCols: false,
        colWrap: false,
        stickyCols: false,
        full: false,
        space: {
            '0': false,
            '1': false,
            '2': false,
        },
        grid: false,
        colHeader: false,
        rowHeader: false,
    },
    validation: {
        fieldName: false,
        validation: {
            accepted: false,
            active_url: false,
            after: false,
            after_or_equal: false,
            alpha: false,
            alpha_dash: false,
            alpha_num: false,
            array: false,
            before: false,
            before_or_equal: false,
            boolean: false,
            completed: false,
            date: false,
            date_equals: false,
            date_format: false,
            different: false,
            digits: false,
            digits_between: false,
            dimensions: false,
            width: false,
            height: false,
            minWidth: false,
            minHeight: false,
            maxWidth: false,
            maxHeight: false,
            ratio: false,
            distinct: false,
            email: false,
            exists: false,
            file: false,
            gt: false,
            gte: false,
            image: false,
            in: false,
            in_array: false,
            integer: false,
            ip: false,
            ipv4: false,
            ipv6: false,
            json: false,
            lt: false,
            lte: false,
            max: false,
            mimetypes: false,
            mimes: false,
            min: false,
            not_in: false,
            not_regex: false,
            nullable: false,
            numeric: false,
            regex: false,
            required: true,
            same: false,
            size: false,
            string: false,
            timezone: false,
            unique: false,
            url: false,
            uuid: false,
        },
        required: true,
        fileRules: {
            min: false,
            max: false,
            mimes: false,
            extensions: false,
            dimensions: false,
            width: false,
            height: false,
            minWidth: false,
            minHeight: false,
            maxWidth: false,
            maxHeight: false,
            ratio: false,
        },
    },
    attributes: {
        disabled: false,
        readonly: false,
        id: false,
        autocomplete: false,
        attrs: false,
    },
};